config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'logout/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'items#index'

  # get "itemdetails", to: "itemdetails#index"
  resources :itemdetails, only: [:index, :show]

  get 'sell/child', to: 'categories#child'
  get 'child', to: 'categories#child'
  get 'sell/grand', to: 'categories#grand'
  get 'grand', to: 'categories#grand'

  get "sell" => "exhibition#index"     # 出品入力画面
  post "create" => "exhibition#create" # 出品

  get 'signups/address' , to: 'signups#address'
  get 'signups/complete' , to: 'signups#complete'
  patch 'signup/address/create' , to: 'signups#address_create'
  get '/users/:user_id/signups/new', to: 'users/signups#sms_send'
  post '/users/:user_id/signups/new', to: 'users/signups#sms_send'
  get 'signup/sms_confirmation' => 'signups#sms_send'
  post 'signup/sms_authenticate' , to: 'signups#sms_authenticate'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'user_confirmations#edit', to: 'user_confirmations#edit'
  devise_scope :user do
    get "sign_in", to: "users/signups#sms_send"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signups#sms_send'
  end
  resources :purchases, only: :new
  resources :users, only: [:new, :index] do
    resources :cards, only: [:index, :new, :destroy, :show] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:new, :create, :edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :index
  end
  resources :cards, only: [:new, :show] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end

  resources :exhibition, only: [:index, :create, :destroy] do
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
      end
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  layout 'application-off'
  def index
  end

  def new
  end

  def show
  end

  def address
  end

  def complete
  end

  def oauth_google
    @user = User.new
    @user.email = session["devise.google_data"]["info"]["unverified_email"]
    @profile = @user.build_profile
  end

  def oauth_facebook
    @user = User.new
    @user.email = session["devise.facebook_data"]['info']['email']
    @profile = @user.build_profile
  end

  def sms_authenticate
    @profile=current_user.profile.assign_attributes(profile_params)
    if  current_user.profile.valid?(:sms_send)
      current_user.profile.update(profile_params)
    else
      @profile=Profile.new
      @errors='未記入の箇所があります。'
      render 'sms_send'
    end
    
  end

  def sms_send
    @profile=Profile.new
    flash.delete(:notice)
  end

  def address_create
    @profile=current_user.profile.assign_attributes(profile_params)
    if current_user.profile.valid?(:value)
      current_user.profile.update(profile_params)
    else
      @profile=current_user.profile
      @errors='未記入の箇所があります。'
      render 'address'
    end
    case params[:move_from]
    when 'signup'
      redirect_to new_user_card_path(current_user.id)
    when 'purchase'
      redirect_to new_item_purchase_path(params[:item_id])
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:phone_number,:first_name, :last_name, :first_name_kana, :last_name_kana, :postalcode, :prefecture, :city, :street_number,:building_name)
  end

  def use_check_address_nil?
    false
  end
end

app/views/signups/_address.html.haml
.delivery
  = form_for(current_user.profile, url: signup_address_create_path) do |f|
    .delivery__title
      %h2 発送元・お届け先住所入力
      .signup-errors
        = @errors
      .delivery__info-container
        %ul
          %li
            %h3 お名前
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :first_name,{class: 'text_field', placeholder: "例) 山田"}
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 太郎"}
          %li
            %h3 お名前カナ
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :first_name_kana,{class: 'text_field', placeholder: "例) ヤマダ"}
          = f.text_field :last_name_kana,{class: 'text_field', placeholder: "例) タロウ"}
          %li
            %h3 郵便番号
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :postalcode,{class: 'text_field', placeholder: "例) 123-4567"}
          %li
            %h3 都道府県
          %li
            .required__icon 必須
          .clearfix
            .input-append
              .select-tag
                = f.collection_select( :prefecture, Prefecture.all, :id, :name)
          %li
            %h3 市町村
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :city,{class: 'text_field', placeholder: '例) 東京都港区'}
          %li
            %h3 番地
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :street_number,{class: 'text_field', placeholder: '例) 芝公園2-1-1'}
          %li
            %h3 建物名
          %li
            .required__icon 任意
          .clearfix
          = f.text_field :building,{class: 'text_field', placeholder: '例) 芝公園ビル223'}
          %li
            %h3 電話
          %li
            .required__icon 任意
          .clearfix
          = f.text_field :phone_number,{class: 'text_field', placeholder: '例) 09012345678'}
          %input{type: 'hidden', name: 'move_from', value: move_from}
          - case local_assigns[:move_from]
            - when 'signup'
              = f.submit '次へ進む', id: 'token', class:'next_btn'
            - when 'purchase'
              %input{type: 'hidden', name: 'item_id', value: item_id}
              = f.submit '変更する', id: 'token', class:'next_btn'
          .clearfix

app/views/signups/address.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header3.png',size: "720x110" , class: "header__bar-img"
= render partial: 'address', locals: { move_from: 'signup' }
= render partial:'items/item_footer'

app/views/signups/complete.haml
%header
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header5.png',size: "680x90" , class: "header__bar-img"
.signup-complete
  .signup__title
    %h2 会員登録完了
    .signup__info-container
      .description
        %span.thanks ありがとうございます。
        %br
        %span.complete 会員登録が完了しました。
        %br/
      .clearfix
    = link_to "メルカリをはじめる",root_path, class:'start-btn'
    .clearfix
    = image_tag 'register_complete_img.png',size: "800x220", class: "register_complete_img"
= render partial:'items/item_footer'

app/views/signups/index.html.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header1.png',size: "670x103" , class: "header__bar-img"
.signup
  = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
    .signup__title
      %h2 会員情報入力
    .signup-errors
      = devise_error_messages!
      = @errors
    .signup__info-container
      %ul
        %li
          %h3 ニックネーム
        %li
          .required__icon 必須
        .clearfix
        = text_field_tag :content, '例) メルカリ太郎',class: 'text_field'
        %li
          %h3 メールアドレス
        %li
          .required__icon 必須
        .clearfix
        = f.email_field :email,{ class: 'text_field', placeholder: "PC・携帯どちらでも可"}
          %li
            %h3 パスワード
          %li
            .required__icon 必須
          .clearfix
          = f.password_field :password,{ class: 'text_field', placeholder: "6文字以上",autocomplete: "off"}
          %li
            %h3 パスワード（確認）
          %li
            .required__icon 必須
          .clearfix
          = f.password_field :password_confirmation,{ class: 'text_field', placeholder: "6文字以上",autocomplete: "off"}
        %li
          %h3 本人確認
        .clearfix
        %li
          %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        = f.fields_for :profile do |f|
          .clearfix
          %li
            %h3 姓（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :family_name,{class: 'text_field', placeholder: "例) 山田"}
          %li
            %h3 名（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 太郎"}
          %li
            %h3 姓カナ（全角)
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :kana_family_name,{class: 'text_field', placeholder: "例) ヤマダ"}
          %li
            %h3 名カナ（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :kana_last_name,{class: 'text_field', placeholder: "例) タロウ"}
          %li
            %h3 生年月日
          %li
            .required__icon 必須
          .clearfix
          = f.date_select( :birth_ymd, use_month_numbers: true, prompt:  '　　---',start_year: 1930, end_year: (Time.now.year - 18), blank:'---',default: Date.new(1989, 1, 1), id:'page_updated_at_1i')
          .clearfix
          .dscription
            %p.gray ※本人情報は正しく入力してください。会員登録後、修正するにはお時間をいただく場合があります。
          = image_tag 'rbot-img.png',size: "325x90" , class: "rbot-img"
          .dscription
            %p「次へ進む」のボタンを押すことにより、
            %p.blue 利用規約
            %p に同意したものとみなします。
          = f.submit('次へ進む' ,class:'next_btn') do
            .next-btn
          .link-box
            %li
              %p 本人情報の登録について
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'items/item_footer' 

app/views/signups/oauth_facebook.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header1.png',size: "670x103" , class: "header__bar-img"
.signup
  = form_for(@user, url: user_registration_path) do |f|
    .signup__title
      %h2 会員情報入力
    .signup-errors
      = @errors
    .signup__info-container
      %ul
        %li
          %h3 ニックネーム
        %li
          .required__icon 必須
        .clearfix
        = f.text_field :nickname,{ autofocus: true ,class: 'text_field', placeholder: "例) メルカリ太郎",autocomplete: "off"}
        %li
          %h3 メールアドレス
        %li
          .required__icon 必須
        .clearfix
        = f.email_field :email,{ class: 'text_field', placeholder: "PC・携帯どちらでも可"}
        -if session["devise.facebook_data"]
            = f.hidden_field :password, value: Devise.friendly_token[0,20]
            = f.hidden_field :password_confirmation, value: Devise.friendly_token[0,20]
        %li
          %h3 本人確認
        .clearfix
        %li
          %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        = f.fields_for :profile do |f|
          .clearfix
          %li
            %h3 姓（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :first_name,{class: 'text_field', placeholder: "例) 山田"}
          %li
            %h3 名（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 太郎"}
          %li
            %h3 姓カナ（全角)
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :first_name_kana,{class: 'text_field', placeholder: "例) ヤマダ"}
          %li
            %h3 名カナ（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name_kana,{class: 'text_field', placeholder: "例) タロウ"}
          %li
            %h3 生年月日
          %li
            .required__icon 必須
          .clearfix
          = f.date_select( :brithday, use_month_numbers: true, prompt:  '　　---',start_year: 1930, end_year: (Time.now.year - 18), blank:'---',default: Date.new(1989, 1, 1), id:'page_updated_at_1i')
          .clearfix
          .dscription
            %p.gray ※本人情報は正しく入力してください。会員登録後、修正するにはお時間をいただく場合があります。
          = image_tag 'rbot-img.png',size: "325x90" , class: "rbot-img"
          .dscription
            %p「次へ進む」のボタンを押すことにより、
            %p.blue 利用規約
            %p に同意したものとみなします。
          
          = f.submit('次へ進む' ,class:'next_btn') do
            .next-btn
          .link-box
            %li
              %p 本人情報の登録について
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'items/item_footer'

app/views/signups/oauth_google.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header1.png',size: "670x103" , class: "header__bar-img"
.signup
  = form_for(@user, url: user_registration_path) do |f|
    .signup__title
      %h2 会員情報入力
    .signup-errors
      = @errors
    .signup__info-container
      %ul
        %li
          %h3 ニックネーム
        %li
          .required__icon 必須
        .clearfix
        = f.text_field :nickname,{ autofocus: true ,class: 'text_field', placeholder: "例) メルカリ太郎",autocomplete: "off"}
        %li
          %h3 メールアドレス
        %li
          .required__icon 必須
        .clearfix
        = f.email_field :email,{ class: 'text_field', placeholder: "PC・携帯どちらでも可"}
        -if session["devise.google_data"]
          = f.hidden_field :password, value: password=Devise.friendly_token[0,20]
          = f.hidden_field :password_confirmation, value: password
        %li
          %h3 本人確認
        .clearfix
        %li
          %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        = f.fields_for :profile do |f|
          .clearfix
          %li
            %h3 姓（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :first_name,{class: 'text_field', placeholder: "例) 山田"}
          %li
            %h3 名（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name,{class: 'text_field', placeholder: "例) 太郎"}
          %li
            %h3 姓カナ（全角)
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :first_name_kana,{class: 'text_field', placeholder: "例) ヤマダ"}
          %li
            %h3 名カナ（全角）
          %li
            .required__icon 必須
          .clearfix
          = f.text_field :last_name_kana,{class: 'text_field', placeholder: "例) タロウ"}
          %li
            %h3 生年月日
          %li
            .required__icon 必須
          .clearfix
          = f.date_select( :brithday, use_month_numbers: true, prompt:  '　　---',start_year: 1930, end_year: (Time.now.year - 18), blank:'---',default: Date.new(1989, 1, 1), id:'page_updated_at_1i')
          .clearfix
          .dscription
            %p.gray ※本人情報は正しく入力してください。会員登録後、修正するにはお時間をいただく場合があります。
          = image_tag 'rbot-img.png',size: "325x90" , class: "rbot-img"
          .dscription
            %p「次へ進む」のボタンを押すことにより、
            %p.blue 利用規約
            %p に同意したものとみなします。
          
          = f.submit('次へ進む' ,class:'next_btn') do
            .next-btn
          .link-box
            %li
              %p 本人情報の登録について
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'items/item_footer'

app/views/signups/show.html.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header2.png',size: "700x120" , class: "header__bar-img"
.signup_sms-2
  .signup__title
    %h2 電話番号認証
    .signup__info-container
      %ul
        %li
          %h3 認証番号
        .clearfix
        = text_field_tag :content,"", placeholder:'認証番号を入力',class: 'text_field'
        .clearfix
        %li
          %p SMSで届いた認証番号を入力してください。
        .clearfix
        .sms-btn_2
          = link_to "認証して完了","/signups/address", class:'sms-btn'
          -#### 仮置き。サーバサイド実装後修正
        .clearfix
    .signup__info-box
    .signup__info-box
      %h3 30秒たっても認証番号が届かない方へ
      %p 電話で認証番号を聞くこともできます。
      .clearfix
      .sms-btn_3
        = link_to "電話で認証番号を聞く（通話無料）", class:'sms-btn'
      .clearfix
    .signup__info-box_2
      %h3 認証番号を再送することもできます。もう一度電話番号を入力してください。
      %p.blue  電話番号を再度入力する
      %br
      .dscription
        ※SMSが届かない場合は
        %span.blue SMS受信設定
        を確認して、もう一度電話番号を入力してください。

= render partial:'items/item_footer' 

app/views/signups/sms_authenticate.html.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header2.png',size: "700x120" , class: "header__bar-img"
.signup_sms-2
  .signup__title
    %h2 電話番号認証
    .signup__info-container
      %ul
        %li
          %h3 認証番号
        .clearfix
        = text_field_tag :content,"", placeholder:'認証番号を入力',class: 'text_field'
        .clearfix
        %li
          %p SMSで届いた認証番号を入力してください。
        .clearfix
        .sms-btn_2
          = link_to "認証して完了",signups_address_path, class:'sms-btn'
        .clearfix
    .signup__info-box
    .signup__info-box
      %h3 30秒たっても認証番号が届かない方へ
      %p 電話で認証番号を聞くこともできます。
      .clearfix
      .sms-btn_3
        = link_to "電話で認証番号を聞く（通話無料）", class:'sms-btn'
      .clearfix
    .signup__info-box_2
      %h3 認証番号を再送することもできます。もう一度電話番号を入力してください。
      %p.blue  電話番号を再度入力する
      %br
      .dscription
        ※SMSが届かない場合は
        %span.blue SMS受信設定
        を確認して、もう一度電話番号を入力してください。

= render partial:'items/item_footer' 

app/views/signups/sms_send.html.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header2.png',size: "700x120" , class: "header__bar-img"
.signup_sms
  = form_for(@profile, url: signup_sms_authenticate_path) do |f|
    .signup__title
      %h2 電話番号の確認
      .signup-errors
        = @errors
      .signup__info-container
        %ul
          %li
            %h3 携帯電話の番号
          .clearfix
          = f.text_field :phone_number,{ class: 'text_field', placeholder: "携帯電話の番号を入力"}
          .clearfix
          %li
            %p 本人確認のため、携帯電話番号のSMS (ショートメッセージサービス)を
            %p 利用して認証を行います。
          .clearfix
          = f.submit('SMSを送信する' ,class:'next_btn')
          .clearfix
            %br
            %p 電話番号は本人確認や不正利用防止のために利用します。
            %p 他のユーザーに公開されることはありません。
          .link-box
            %li
              %p 電話番号の確認が必要な理由
            %li
              = fa_icon 'chevron-right', class:'arrow_blue'
          .clearfix

= render partial:'items/item_footer' 