config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'logout/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'items#index'

  # get "itemdetails", to: "itemdetails#index"
  resources :itemdetails, only: [:index, :show]

  get 'sell/child', to: 'categories#child'
  get 'child', to: 'categories#child'
  get 'sell/grand', to: 'categories#grand'
  get 'grand', to: 'categories#grand'

  get "sell" => "exhibition#index"     # 出品入力画面
  post "create" => "exhibition#create" # 出品

  get 'signups/address' , to: 'signups#address'
  get 'signups/complete' , to: 'signups#complete'
  patch 'signup/address/create' , to: 'signups#address_create'
  get '/users/:user_id/signups/new', to: 'users/signups#sms_send'
  post '/users/:user_id/signups/new', to: 'users/signups#sms_send'
  get 'signup/sms_confirmation' => 'signups#sms_send'
  post 'signup/sms_authenticate' , to: 'signups#sms_authenticate'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'user_confirmations#edit', to: 'user_confirmations#edit'
  devise_scope :user do
    get "sign_in", to: "users/signups#sms_send"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signups#sms_send'
  end
  resources :purchases, only: :new
  resources :users, only: [:new, :index] do
    resources :cards, only: [:index, :new, :destroy, :show] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:new, :create, :edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :index
  end
  resources :cards, only: [:new, :show] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end

  resources :exhibition, only: [:index, :create, :destroy] do
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_one :card, dependent: :destroy
  accepts_nested_attributes_for :card
  validates :password, presence: true, length: { minimum: 6 }, format: { with: /\A(?=.*?[a-z])[a-z\d]+\z/i }
  validates :password_confirmation, presence: true, length: { minimum: 6 }
  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true

  def self.profile_with_user_is_valid?(params)
    params[:user][:profile_attributes][:first_name].present?\
    && params[:user][:profile_attributes][:last_name].present?\
    && params[:user][:profile_attributes][:first_name_kana].present?\
    && params[:user][:profile_attributes][:last_name_kana].present?\
    && params[:user][:profile_attributes][:'brithday(1i)'].present?\
    && params[:user][:profile_attributes][:'brithday(2i)'].present?\
    && params[:user][:profile_attributes][:'brithday(3i)'].present?
  end

  def self.from_omniauth(auth)
    @credential = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    @user = User.where(email:auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.password_confirmation = Devise.friendly_token[0,20] 
      end
    @user
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to "/signup/#{provider}"
    end
  end

  def failure
    redirect_to top_index_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'application-off'
  # GET /resource/sign_up
  # def new
  #   super
  # end

  def new
    @user = User.new
    @profile = @user.build_profile
  end

  # POST /resource
  def create
    if User.profile_with_user_is_valid?(params)
       super and return
    else
      @user =build_resource(sign_up_params)
      @profile = @user.profile
      @errors='未記入の箇所があります。'
      render 'new' and return
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
    signup_sms_confirmation_path
 end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'application-off'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render layout: 'application-off.haml'
  end

  def show
    @user = User.find(current_user.id)
  end

  def index
  end
end

app/views/users/_user_sidebar.html.haml
.side-content
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          マイページ
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          お知らせ
          %span.notice-number
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          やることリスト
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          いいね！一覧
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          出品する
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          出品した商品 - 出品中
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          出品した商品 - 取引中
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          出品した商品 - 売却済み
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          購入した商品 - 取引中
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          出品した商品 - 過去の取引
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          ニュース一覧
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          評価一覧
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          ガイド
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          お問い合わせ
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
    %h3.mypage-nav__head メルペイ
    %ul.mypage-nav__list
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          売上・振込申請
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          ポイント
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
    %h3.mypage-nav__head 設定
    %ul.mypage-nav__list
      %li.mypage-nav__item
        = link_to "/users/1/user_profiles/1/edit", class: 'mypage-nav__item__link' do
          プロフィール
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          発送・お届け先住所変更
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to user_cards_path(current_user), class: 'mypage-nav__item__link' do
          お支払い方法
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to users_path(current_user), class: 'mypage-nav__item__link' do
          メール/パスワード
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to "/users/1/user_confirmations/1/edit", class: 'mypage-nav__item__link' do
          本人情報
          %i.fa.fa-arrow-right{"aria-hidden": "true"}
      %li.mypage-nav__item
        = link_to user_logouts_path(current_user), class: 'mypage-nav__item__link active' do
          ログアウト
          %i.fa.fa-arrow-right{"aria-hidden": "true"}

app/views/users/index.html.haml
- breadcrumb :mypage
%main.mypage-default
  .mypage-default__wrapper.clearfix
    .main-content
      %section.user-desc
        = link_to users_path(current_user), class: 'user-desc__link' do
          .user-image
            = image_tag("member_photo_noimage_thumb.png")
          %h2.user-name ユーザー
          .user-numders
            .user-numders__item
              評価
              %span 2
            .user-numders__item
              出品数
              %span 0
      %section.user-content
        %ul.content-tabs
          %li.content-tabs__item.active{data: {tab: 1}}
            %h3 お知らせ
          %li.content-tabs__item{data: {tab: 2}}
            %h3 やることリスト
        .user-notification
          %ul.user-notification__list.active{data: {tab: 1}}
            %li.user-notification__item
              = link_to users_path(current_user), class: 'user-notification__item__link' do
                .notice-image
                  = image_tag("mercari_profile.png")
                .notice-body
                  .notice-body__text
                    《SHOPLISTで最大10%OFF》“メルペイだけ“の期間限定キャンペーン開催中！
                  .notice-body__time
                    %i.fa.fa-clock-o{"aria-hidden": "true"}
                    %span ３時間前
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.user-notification__item
              = link_to users_path(current_user), class: 'user-notification__item__link' do
                .notice-image
                  = image_tag("mercari_profile.png")
                .notice-body
                  .notice-body__text
                    《SHOPLISTで最大10%OFF》“メルペイだけ“の期間限定キャンペーン開催中！
                  .notice-body__time
                    %i.fa.fa-clock-o{"aria-hidden": "true"}
                    %span ３時間前
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.user-notification__item
              = link_to users_path(current_user), class: 'user-notification__item__link' do
                .notice-image
                  = image_tag("mercari_profile.png")
                .notice-body
                  .notice-body__text
                    《SHOPLISTで最大10%OFF》“メルペイだけ“の期間限定キャンペーン開催中！
                  .notice-body__time
                    %i.fa.fa-clock-o{"aria-hidden": "true"}
                    %span ３時間前
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.user-notification__item
              = link_to users_path(current_user), class: 'user-notification__item__link' do
                .notice-image
                  = image_tag("mercari_profile.png")
                .notice-body
                  .notice-body__text
                    《SHOPLISTで最大10%OFF》“メルペイだけ“の期間限定キャンペーン開催中！
                  .notice-body__time
                    %i.fa.fa-clock-o{"aria-hidden": "true"}
                    %span ３時間前
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.user-notification__item
              = link_to users_path(current_user), class: 'user-notification__item__link' do
                .notice-image
                  = image_tag("mercari_profile.png")
                .notice-body
                  .notice-body__text
                    《SHOPLISTで最大10%OFF》“メルペイだけ“の期間限定キャンペーン開催中！
                  .notice-body__time
                    %i.fa.fa-clock-o{"aria-hidden": "true"}
                    %span ３時間前
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.content-list-page
              = link_to users_path(current_user), class: 'content-list-page__link' do
                一覧を見る
          %ul.user-notification__list{data: {tab: 2}}
            %li.user-notification__no-item
              現在、やることリストはありません
      %section.user-shoping-data
        %h2.user-shoping-data__head 購入した商品
        %ul.content-tabs
          %li.content-tabs__item{data: {tab: 1}}
            %h3 取引中
          %li.content-tabs__item.active{data: {tab: 2}}
            %h3 過去の取引
        .user-shoping-data__list
          %ul.shoping-list{data: {tab: 1}}
            %li.shoping-list__no-item
              取引中の商品がありません
          %ul.shoping-list.active{data: {tab: 2}}
            %li.shoping-list__item
              = link_to users_path(current_user), class: 'shoping-list__item__link' do
                .shoping-list-image
                  = image_tag("mercari_icon.png")
                .shoping-list-body
                  .shoping-list-body__text
                    「○○○○○○○○○○○○○○○○○」を購入しました。取引が完了しました
                  .shoping-list-body__state
                    取引完了
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.shoping-list__item
              = link_to users_path(current_user), class: 'shoping-list__item__link' do
                .shoping-list-image
                  = image_tag("mercari_icon.png")
                .shoping-list-body
                  .shoping-list-body__text
                    「○○○○○○○○○○○○○○○○○」を購入しました。取引が完了しました
                  .shoping-list-body__state
                    取引完了
                %i.fa.fa-arrow-right{"aria-hidden": "true"}
            %li.content-list-page
              = link_to users_path(current_user), class: 'content-list-page__link' do
                一覧を見る
    =render partial: "users/user_sidebar"

app/views/users/new.html.haml
%header
  = image_tag 'mercari_logo_horizontal.png',size: "234x76" , class: "header__logo-img"
.user
  .user__title
    %h2 新規会員登録
    .user__btn_container
      .user__btn_mail
        = fa_icon 'envelope', class:'mail-icon'
        = link_to "メールアドレスで登録",new_user_registration_path
        -#### 仮置き。サーバサイド実装後、修正
      .user__btn_fb
        = image_tag 'facebook_icon.png',size: "35x35" , class: "facebook-icon "
        = link_to "Facebookで登録",user_facebook_omniauth_authorize_path
      .user__btn_google
        = image_tag 'google_icon.png',size: "37x37" , class: "google-icon "
        = link_to "Googleで登録",user_google_oauth2_omniauth_authorize_path

= render partial:'items/item_footer' 