config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'logout/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'items#index'

  # get "itemdetails", to: "itemdetails#index"
  resources :itemdetails, only: [:index, :show]

  get 'sell/child', to: 'categories#child'
  get 'child', to: 'categories#child'
  get 'sell/grand', to: 'categories#grand'
  get 'grand', to: 'categories#grand'

  get "sell" => "exhibition#index"     # 出品入力画面
  post "create" => "exhibition#create" # 出品

  get 'signups/address' , to: 'signups#address'
  get 'signups/complete' , to: 'signups#complete'
  patch 'signup/address/create' , to: 'signups#address_create'
  get '/users/:user_id/signups/new', to: 'users/signups#sms_send'
  post '/users/:user_id/signups/new', to: 'users/signups#sms_send'
  get 'signup/sms_confirmation' => 'signups#sms_send'
  post 'signup/sms_authenticate' , to: 'signups#sms_authenticate'
  get 'signup/google' , to: 'signups#oauth_google'
  get 'signup/facebook' , to: 'signups#oauth_facebook'
  get 'user_confirmations#edit', to: 'user_confirmations#edit'
  devise_scope :user do
    get "sign_in", to: "users/signups#sms_send"
    get "sign_out", to: "users/sessions#destroy"
    post 'signup/sms_confirmation' => 'signups#sms_send'
  end
  resources :purchases, only: :new
  resources :users, only: [:new, :index] do
    resources :cards, only: [:index, :new, :destroy, :show] do
      collection do
        get 'add', to: 'cards#add'
        post 'pay', to: 'cards#pay'
      end
    end
    resources :user_profiles, only: [:new, :create, :edit, :update]
    resources :user_confirmations, only: [:create, :edit, :update]
    resources :logouts, only: :index
  end
  resources :cards, only: [:new, :show] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end

  resources :exhibition, only: [:index, :create, :destroy] do
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true, uniqueness: true
  validates :card_id, presence: true, uniqueness: true
  validates :customer_id, presence: true, uniqueness: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
   require 'payjp'

   def index # カード追加ボタン表示 or カード情報&削除ボタン表示
      @card = current_user.card
      if @card
         Payjp.api_key = Rails.application.credentials.payjp[:test_secret_key]
         customer = Payjp::Customer.retrieve(@card.customer_id)
         @default_card_information = customer.cards.retrieve(@card.card_id)
      end
   end

   def new
      gon.payjp_test_pk = Rails.application.credentials.payjp[:test_public_key]
      render layout: 'application-off.haml'
   end
   def show
      render layout: 'application-off.haml'
   end

   def add
      gon.payjp_test_pk = Rails.application.credentials.payjp[:test_public_key]
   end

   def pay
      Payjp.api_key = Rails.application.credentials.payjp[:test_secret_key]
      if card_params.blank?
         flash[:alert] = '入力されたカード情報が不正です'
         case card_params[:move_from_action]
         when 'add'
            redirect_to action: :add, notice: '入力されたカード情報が不正です'
         when 'new'
            redirect_to action: :new, notice: '入力されたカード情報が不正です'
         when 'purchase'
            redirect_to card_item_purchases_path(params[:item_id]), notice: '入力されたカード情報が不正です'
         end
      else
         customer = Payjp::Customer.create(
            description: '登録テスト', 
            email: current_user.email, 
            card: params[:payjp_token],
            metadata: {user_id: current_user.id}
            ) 
            @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
            
         if @card.save
         
         case card_params[:move_from_action]
            when 'add'
               flash[:notice] = 'クレジットカードを登録しました'
               redirect_to action: :index
            when 'new'
               redirect_to signups_complete_path
            when 'purchase'
               redirect_to new_item_purchase_path(params[:item_id])
            end
         else
            flash[:alert] = '入力されたカード情報が不正です'
            case card_params[:move_from_action]
            when 'add'
               redirect_to action: :add, notice: '入力されたカード情報が不正です'
            when 'new'
               redirect_to action: :new, notice: '入力されたカード情報が不正です'
            when 'purchase'
               redirect_to card_item_purchases_path(params[:item_id]), alert: '入力されたカード情報が不正です'
            end
         end
      end
   end

   def destroy #PayjpとCardデータベースを削除
      card = Card.find_by(user_id: current_user.id)
      if card.present?
        Payjp.api_key = Rails.application.credentials.payjp[:test_secret_key]
        customer = Payjp::Customer.retrieve(card.customer_id)
        customer.delete
        card.destroy
        flash[:notice] = 'クレジットカードを削除しました'
        case params[:move_from]
          when 'purchase'
            redirect_to new_item_purchase_path(params[:item_id]), notice: 'クレジットカードを削除しました'
            return
          else
            redirect_to action: :index, notice: 'クレジットカードを削除しました'
            return
        end
      else
        flash[:alert] = 'クレジットカードが登録されていません'
        redirect_to action: :index
      end
   end

   private

   def card_params
      params.permit(:payjp_token, :move_from_action)
   end
end

app/helpers/cards_helper.rb
module CardsHelper
  def get_card_exp_year
    {'19':'19','20':'20','21':'21','22':'22','23':'23','24':'24','25':'25','26':'26','27':'27','28':'28','29':'29'}
  end

  def get_card_exp(info)
    sprintf "%<month>02d / %{year}", month: info.exp_month, year: info.exp_year.to_s[2, 2]
  end

end

app/views/cards/_cards_detail.haml
= form_tag(pay_user_cards_path(current_user), method: :post, id: 'charge-form',  name: 'inputForm', class: 'credit__box_list') do
  %span カード番号
  .required__icon 必須
  .clearfix
  = text_field_tag :number, '', class: 'text_field number', placeholder: '半角数字のみ', maxlength: '16', type: 'text', id: 'card_number'
  = image_tag 'credit_card_icon.png',size: '380x50' , class: 'credit__logo-img'
  .credit__box_expiration_date
    %span 有効期限
    .required__icon 必須
  .clearfix
  = date_select :exp_month, :updated_at, class: 'date_select', use_month_numbers: true, discard_year: true, discard_day: true, type: 'text'
  %sub.month 月
  .clearfix
  = select_tag :exp_year, options_for_select(get_card_exp_year),class: 'select-tag', type: 'text'
  %sub 年
  .credit__box_security_code
    %br
    %span セキュリティコード
    .required__icon 必須
    .clearfix
    = text_field_tag :cvc, '',  class: 'text_field', id: 'cvc', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: '3'

  .credit__box_question
    %span.icon_question ?
    %p カード裏面の番号とは？
  #card_token
    %input{type: 'hidden', name: 'move_from_action', value: move_from_action}
  - case local_assigns[:move_from_action]
    - when 'add'
      = submit_tag '追加する', id: 'token_submit', class:'credit_card redbtn'
    - when 'new'
      = submit_tag '次へ進む', id: 'token_submit', class:'credit_card redbtn'

app/views/cards/_cards_main.haml
.credit
  .credit__title
    %h2 支払い方法
  .credit__box_list
    %p クレジットカード一覧
    - if @default_card_information
      .credit__btn_add
        = form_tag('/users/1/cards/1', method: :delete, id: 'charge-form',  name: "inputForm") do
          -#### 仮置き "/users/#{current_user.id}/cards/#{@card.id}"
          %input{ type: "hidden", name: "card_id", value: "" }
          %button{class: 'redbtn'} 削除する
    - else
      .credit__btn_add
        = fa_icon 'credit-card', class:'credit-card'
        = link_to "クレジットカードを追加する", add_user_cards_path(current_user) , class:'credit_card',  data: {turbolinks: false}
      
  .box__bottom_line
  .credit__box_link
    %p
      %p 支払い方法について
    %p
      = fa_icon 'chevron-right', class:'arrow_blue'

app/views/cards/add.haml
- breadcrumb :cards_add
.mypage-default
  .mypage-default__wrapper.clearfix
    = render partial:'users/user_sidebar'
    .credit_2
      .credit__title
        %h2 クレジットカード情報入力
      = render partial:'cards/cards_detail', locals: { move_from_action: "add" }

app/views/cards/index.html.haml
- breadcrumb :cards_index
.mypage-default
  .mypage-default__wrapper.clearfix
    = render partial: 'users/user_sidebar'
    = render partial: 'cards_main', locals: { move_from: 'card' }

app/views/cards/new.haml
%headers
  = link_to(root_path) do
    = image_tag "logo.svg", width:  "234", height: "76", class: "header__logo-img_signup"
  = image_tag 'signup_header4.png',size: "690x90" , class: "header__bar-img"
.user_mypage
.user_mypage__container
  .credit_3
    .credit__title
      %h2 支払い方法
    = render partial:'cards/cards_detail', locals: { move_from_action: "new" }
= render partial:'items/item_footer'

app/views/cards/show.html.haml
%header
  = image_tag 'mercari_logo_horizontal.png',size: "234x76" , class: "header__logo-img_signup"
.signup-complete
  .signup__title
    %h2 会員登録完了
    .signup__info-container
      .description
        %span.thanks ありがとうございます。
        %br
        %span.complete 会員登録が完了しました。
      .clearfix
    .start-btn
      = link_to "メルカリをはじめる","/users/1", class:'sms-btn'
      -#### 仮置き。サーバサイド実装後、修正
    .clearfix
    = image_tag 'register_complete_img.png',size: "800x300", class: "register_complete_img"
= render partial:'items/item_footer' 